name: Trigger auto deployment for nextjsaca2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/nextjsaca2-AutoDeployTrigger-a258ed14-7a6f-4a64-93a8-c5d932924ed0.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.NEXTJSACA2_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.NEXTJSACA2_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.NEXTJSACA2_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.NEXTJSACA2_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.NEXTJSACA2_REGISTRY_PASSWORD }}
          containerAppName: nextjsaca2
          resourceGroup: nextjsacarg
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


